# Generated by Django 5.0.6 on 2024-07-31 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
