# Generated by Django 5.0.6 on 2024-08-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_rename_firstname_userdetails_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='username',
        ),
    ]
