# Generated by Django 5.0.6 on 2024-08-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_remove_userdetails_confirm_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='type',
            field=models.IntegerField(blank=True, choices=[('user', 'user'), ('admin', 'admin')], max_length=5, null=True),
        ),
    ]
