# Generated by Django 5.0.6 on 2024-08-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_userdetails_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='type',
            field=models.IntegerField(blank=True, choices=[('user', 'user'), ('admin', 'admin')], null=True),
        ),
    ]
