# Generated by Django 5.0.6 on 2024-08-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_alter_userdetails_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 star'), (2, '2 star'), (3, '3 star'), (4, '4 star'), (5, '5 star')]),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='type',
            field=models.CharField(blank=True, choices=[('user', 'user'), ('admin', 'admin')], max_length=5, null=True),
        ),
    ]
